### ISSUE TITLE
Support for mono repo

### ISSUE THREAD

**Issue by remonh87** [mmcc007/sylph#58]
In our project we use a monorepo and we have a structure like:

- Root
       -- apps
             --- app1 (sylph.yaml and flutter drive test is located here)
      -- pkgs
            --- feature1
           --- feature2

When we run sylph we receive the following error: 

`Because app1 depends on feature1 from path which doesn't exist (could not find package feature1 at "../../pkgs/feature1"), version solving failed.`

The app builds correctly when running `flutter build`. 

Does sylph support our structure at the moment and if not are there any plans for supporting monorepo's ?

Keep up the good work!

stacktrace: 
```
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _AsyncAwaitCompleter.completeError
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                    progress
    | package:pub/src/solver.dart 32:10                  resolveVersions
    | package:pub/src/entrypoint.dart 203:24             Entrypoint.acquireDependencies
---- End log transcript ----
pub get failed (66)
Unhandled exception:
command failed: cmd='flutter packages get'
#0      cmd (package:sylph/src/utils.dart:43:5)
#1      bundleFlutterTests (package:sylph/src/bundle.dart:52:3)
<asynchronous suspension>
#2      sylphRun (package:sylph/src/sylph_run.dart:48:9)
<asynchronous suspension>
#3      main (file:///Users/user/.pub-cache/hosted/pub.dartlang.org/sylph-0.4.0/bin/main.dart:80:13)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by mmcc007** [comment]
Can you provide the stack trace?

**Comment by remonh87** [comment]
updated my comment

**Comment by mmcc007** [comment]
_sylph_ currently assumes the app does not have local package dependencies.

One way to add support for mono repos is to copy the local package dependencies into the app dir during bundling. The local package dependencies can be found by scanning the app's pubspec.yaml. Then update the app's pubspec.yaml to find the new local package dependencies.

**Comment by remonh87** [comment]
thanks for thinking along but this sound quite difficult to accomplish in CI. I will look a bit further for another solution ticket can be closed

**Comment by mmcc007** [comment]
Added support for handling local packages during bundling. Try it out using:
```
git clone https://github.com/mmcc007/sylph.git
cd sylph
git checkout #58_local_deps
pub global activate --source path .
cd <one of your app dirs>
sylph
```

**Comment by remonh87** [comment]
thank you for the help! works like a charm!

**Comment by mmcc007** [comment]
Great! Thanks for checking it out.
