### ISSUE TITLE
Is it possible to upgrade Bundles Appium to version v1.15.1 using `test_spec.yaml`?

### ISSUE THREAD

**Issue by chinnonsantos** [mmcc007/sylph#85]
**`Test_spec.yaml`** has this:

https://github.com/mmcc007/sylph/blob/908b4ab6fb53275f3236ca7746d1bb6e294c4eb4/lib/resources/test_spec.yaml#L9-L15

Is this limited between **1.6.5** and **1.8.1**? Or can I set the latest version (**v1.15.1**)?

**Comment by mmcc007** [comment]
These are old comments that came with the original test_spec.yaml. They are intended for appium testers. Sylph does not use appium.
