### ISSUE TITLE
Invalid argument: Cannot find executable for 7z

### ISSUE THREAD

**Issue by Malone5923** [mmcc007/sylph#93]
So Im trying to run sylph for integration test for AWS device farm. I have followed the instructions for installation and configuration but I am unable to get it to work. Some clarification would be needed as to what Im doing wrong. Below is the log

C:\Users\penedeh\Desktop\Digital Bank Mobile>sylph -c sylph.yaml -v
[  +30 ms] Starting Sylph run 'sylph run 2020-03-09 07:19:38.482' on AWS Device Farm ...
[  +10 ms] Config file: sylph.yaml
[+6230 ms] executing: [.\] aws devicefarm list-devices
[+2566 ms] executing: [.\] aws devicefarm list-projects
[   +2 ms] Creating new project for 'App Integration Tests' ...
[+2709 ms] executing: [.\] aws devicefarm create-project --name App Integration Tests --default-job-timeout-minutes 10
[   +5 ms] Unpacking sylph resources to /tmp/sylph
[+4094 ms] Creating test bundle for upload...
Unhandled exception:
Invalid argument(s): Cannot find executable for 7z.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      cmd (package:sylph/src/base/utils.dart:106:33)
#3      zip (package:sylph/src/base/utils.dart:82:5)
#4      bundleFlutterTests (package:sylph/src/bundle.dart:48:3)
#5      sylphRun (package:sylph/src/sylph_run.dart:59:3)
<asynchronous suspension>
#6      run (file:///C:/Users/penedeh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/sylph-0.7.2/bin/main.dart:97:35)
<asynchronous suspension>
#7      main.<anonymous closure> (file:///C:/Users/penedeh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/sylph-0.7.2/bin/main.dart:56:13)
#8      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1465:12)
#13     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#14     runInContext (package:sylph/src/context_runner.dart:11:24)
#15     main (file:///C:/Users/penedeh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/sylph-0.7.2/bin/main.dart:55:11)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[  +38 ms] Starting Sylph run 'sylph run 2020-03-09 07:20:32.603' on AWS Device Farm ...
[  +13 ms] Config file: sylph.yaml
[+6344 ms] executing: [.\] aws devicefarm list-devices
[+6459 ms] executing: [.\] aws devicefarm list-projects
[   +2 ms] Unpacking sylph resources to /tmp/sylph
[+3213 ms] Creating test bundle for upload...
Unhandled exception:
Invalid argument(s): Cannot find executable for 7z.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      cmd (package:sylph/src/base/utils.dart:106:33)
#3      zip (package:sylph/src/base/utils.dart:82:5)
#4      bundleFlutterTests (package:sylph/src/bundle.dart:48:3)
#5      sylphRun (package:sylph/src/sylph_run.dart:59:3)
<asynchronous suspension>
#6      run (file:///C:/Users/penedeh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/sylph-0.7.2/bin/main.dart:97:35)
<asynchronous suspension>
#7      main.<anonymous closure> (file:///C:/Users/penedeh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/sylph-0.7.2/bin/main.dart:56:13)
#8      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:154:29)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1465:12)
#13     AppContext.run (package:tool_base/src/base/context.dart:153:18)
#14     runInContext (package:sylph/src/context_runner.dart:11:24)
#15     main (file:///C:/Users/penedeh/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/sylph-0.7.2/bin/main.dart:55:11)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by mmcc007** [comment]
Looks like you need to install 7z or make sure it is in your path. https://www.7-zip.org/

**Comment by Malone5923** [comment]
Yes, I realized that after a good nap and got it working eventually. I appreciate the quick response.
